repos:
-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: ^testing/(data|examples)/
        additional_dependencies: [flake8-docstrings]

