name: flim
channels:
  - pytorch
  - defaults
dependencies:
  - torch>=1.10.0
  - torchvision>=0.11.2
  - pip>=21.2.0
  - pip:
    - napari[pyqt5]
    - numpy>=1.20
    - setuptools>=62.3.2
    - scikit-image>=0.19.2
    - scikit-learn>=1.0.0
    - pylint
    - pep8
    - pyflakes
    - mccabe
    - pydocstyle
    - flake8
    - pylama
    - termcolor>=1.1.0 
    - numba>=0.55.2
    - nibabel>=3.2.2
    - napari[pyqt5]
    - magicgui